import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import { Header1 } from "@/components/ui/header";
import { Footer2 } from "@/components/ui/shadcnblocks-com-footer2";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>   
        <Header1   />
        {children}
        <Footer2 />
      </body>
    </html>
  );
}
